import { AnalysisResponse } from "@/types/api";
import { 
  FileText, 
  Download, 
  Share2, 
  Copy, 
  Check, 
  Printer,
  Mail,
  Network,
  BarChart3,
  AlertTriangle,
  Lightbulb,
  Calendar,
  Clock
} from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogTrigger,
  DialogDescription 
} from "@/components/ui/dialog";
import { toast } from "sonner";

interface ReportSectionProps {
  data: AnalysisResponse;
}

export function ReportSection({ data }: ReportSectionProps) {
  const [copied, setCopied] = useState(false);
  const [generating, setGenerating] = useState(false);

  const reportDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const reportTime = new Date().toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  });

  // Calculate summary statistics
  const totalCells = Object.values(data.topology).flat().length;
  const totalLinks = Object.keys(data.topology).length;
  const avgConfidence = Math.round(
    Object.values(data.topology_confidence).reduce((a, b) => a + b, 0) / totalLinks
  );
  const totalEvents = Object.values(data.root_cause_attribution).flat().length;
  const avgSavings = Math.round(
    Object.values(data.bandwidth_savings_pct).reduce((a, b) => a + b, 0) / totalLinks
  );

  // Generate recommendations based on data
  const recommendations = [
    {
      priority: "high",
      title: "Optimize Link 1 Capacity",
      description: `Link 1 shows ${data.topology_confidence["1"]}% confidence with potential ${data.bandwidth_savings_pct["1"]}% bandwidth savings through statistical multiplexing.`,
    },
    {
      priority: "medium", 
      title: "Monitor Cell 4 Traffic",
      description: "Cell 4 is the sole contributor to Link 1 congestion events. Consider load balancing strategies.",
    },
    {
      priority: "medium",
      title: "Review Link 3 Topology",
      description: `Link 3 has the highest confidence (${data.topology_confidence["3"]}%) and most cells (${data.topology["3"].length}). Validate topology accuracy.`,
    },
    {
      priority: "low",
      title: "Implement Buffer Optimization",
      description: `With buffering, capacity estimates show ~22% reduction. Evaluate trade-offs for latency-sensitive traffic.`,
    },
  ];

  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    toast.success("Report link copied to clipboard");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadReport = () => {
    setGenerating(true);
    
    // Generate report content
    const reportContent = `
O-RAN FRONTHAUL OPTIMIZATION REPORT
Generated: ${reportDate} at ${reportTime}
=====================================

EXECUTIVE SUMMARY
-----------------
• Total Cells Analyzed: ${totalCells}
• Fronthaul Links Detected: ${totalLinks}
• Average Topology Confidence: ${avgConfidence}%
• Congestion Events Detected: ${totalEvents}
• Average Bandwidth Savings Potential: ${avgSavings}%

TOPOLOGY ANALYSIS
-----------------
${Object.entries(data.topology).map(([linkId, cells]) => 
  `Link ${linkId}: ${cells.length} cells (${cells.join(", ")}) - ${data.topology_confidence[linkId]}% confidence`
).join("\n")}

CAPACITY ANALYSIS
-----------------
${Object.entries(data.capacity.no_buffer_gbps).map(([linkId, capacity]) => 
  `Link ${linkId}: ${capacity.toFixed(2)} Gbps (no buffer) / ${data.capacity.with_buffer_gbps[linkId].toFixed(2)} Gbps (with buffer)`
).join("\n")}

BANDWIDTH SAVINGS
-----------------
${Object.entries(data.bandwidth_savings_pct).map(([linkId, savings]) => 
  `Link ${linkId}: ${savings}% potential savings`
).join("\n")}

CONGESTION EVENTS
-----------------
${Object.entries(data.root_cause_attribution).map(([linkId, events]) => 
  `Link ${linkId}: ${events.length} events detected`
).join("\n")}

RECOMMENDATIONS
---------------
${recommendations.map((rec, idx) => 
  `${idx + 1}. [${rec.priority.toUpperCase()}] ${rec.title}\n   ${rec.description}`
).join("\n\n")}

---
Report generated by O-RAN Fronthaul Optimizer v2.4.1
    `.trim();

    // Create and download file
    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `oran-fronthaul-report-${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setTimeout(() => {
      setGenerating(false);
      toast.success("Report downloaded successfully");
    }, 1000);
  };

  const handlePrint = () => {
    window.print();
    toast.success("Print dialog opened");
  };

  const handleEmailReport = () => {
    const subject = encodeURIComponent("O-RAN Fronthaul Optimization Report");
    const body = encodeURIComponent(`
Please find the O-RAN Fronthaul Optimization Report summary below:

• Total Cells: ${totalCells}
• Links Detected: ${totalLinks}  
• Avg Confidence: ${avgConfidence}%
• Congestion Events: ${totalEvents}

View full report: ${window.location.href}
    `);
    window.open(`mailto:?subject=${subject}&body=${body}`);
    toast.success("Email client opened");
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="section-card">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="p-3 bg-primary/10 rounded-xl">
              <FileText className="w-6 h-6 text-primary" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-foreground">Analysis Report</h2>
              <p className="text-sm text-muted-foreground">
                Comprehensive network optimization summary
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Calendar className="w-4 h-4" />
            <span>{reportDate}</span>
            <Clock className="w-4 h-4 ml-2" />
            <span>{reportTime}</span>
          </div>
        </div>

        {/* Quick Actions */}
        <div className="flex flex-wrap gap-3">
          <Button onClick={handleDownloadReport} disabled={generating} className="gap-2">
            <Download className="w-4 h-4" />
            {generating ? "Generating..." : "Download Report"}
          </Button>
          
          <Button variant="outline" onClick={handleCopyLink} className="gap-2">
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? "Copied!" : "Copy Link"}
          </Button>
          
          <Button variant="outline" onClick={handlePrint} className="gap-2">
            <Printer className="w-4 h-4" />
            Print
          </Button>
          
          <Button variant="outline" onClick={handleEmailReport} className="gap-2">
            <Mail className="w-4 h-4" />
            Email
          </Button>

          <Dialog>
            <DialogTrigger asChild>
              <Button variant="secondary" className="gap-2">
                <Share2 className="w-4 h-4" />
                Share Options
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Share Report</DialogTitle>
                <DialogDescription>
                  Choose how you want to share this analysis report
                </DialogDescription>
              </DialogHeader>
              <div className="grid gap-3 py-4">
                <Button variant="outline" onClick={handleCopyLink} className="justify-start gap-3">
                  <Copy className="w-4 h-4" />
                  Copy shareable link
                </Button>
                <Button variant="outline" onClick={handleEmailReport} className="justify-start gap-3">
                  <Mail className="w-4 h-4" />
                  Send via email
                </Button>
                <Button variant="outline" onClick={handleDownloadReport} className="justify-start gap-3">
                  <Download className="w-4 h-4" />
                  Download as file
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Report Sections Grid */}
      <div className="grid md:grid-cols-2 gap-6">
        {/* Topology Summary */}
        <div className="section-card">
          <div className="flex items-center gap-2 mb-4">
            <Network className="w-5 h-5 text-chart-1" />
            <h3 className="font-semibold">Topology Summary</h3>
          </div>
          <div className="space-y-3">
            {Object.entries(data.topology).map(([linkId, cells]) => (
              <div key={linkId} className="flex items-center justify-between p-3 bg-muted/30 rounded-lg">
                <div>
                  <span className="font-medium">Link {linkId}</span>
                  <span className="text-sm text-muted-foreground ml-2">
                    ({cells.length} cells)
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <div className="text-sm font-mono px-2 py-0.5 bg-primary/10 text-primary rounded">
                    {data.topology_confidence[linkId]}% conf
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Capacity Summary */}
        <div className="section-card">
          <div className="flex items-center gap-2 mb-4">
            <BarChart3 className="w-5 h-5 text-chart-2" />
            <h3 className="font-semibold">Capacity Analysis</h3>
          </div>
          <div className="space-y-3">
            {Object.entries(data.capacity.no_buffer_gbps).map(([linkId, capacity]) => (
              <div key={linkId} className="p-3 bg-muted/30 rounded-lg">
                <div className="flex items-center justify-between mb-2">
                  <span className="font-medium">Link {linkId}</span>
                  <span className="text-xs px-2 py-0.5 bg-status-high/10 text-status-high rounded">
                    {data.bandwidth_savings_pct[linkId]}% savings
                  </span>
                </div>
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div>
                    <span className="text-muted-foreground">No buffer:</span>
                    <span className="ml-2 font-mono">{capacity.toFixed(2)} Gbps</span>
                  </div>
                  <div>
                    <span className="text-muted-foreground">With buffer:</span>
                    <span className="ml-2 font-mono">{data.capacity.with_buffer_gbps[linkId].toFixed(2)} Gbps</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Risk Summary */}
        <div className="section-card">
          <div className="flex items-center gap-2 mb-4">
            <AlertTriangle className="w-5 h-5 text-status-medium" />
            <h3 className="font-semibold">Congestion Risk</h3>
          </div>
          <div className="space-y-3">
            {Object.entries(data.root_cause_attribution).map(([linkId, events]) => {
              const topContributors = events
                .flatMap((e) => e.contributors)
                .reduce((acc, c) => {
                  acc[c.cell_id] = (acc[c.cell_id] || 0) + c.pct;
                  return acc;
                }, {} as Record<number, number>);
              
              const sortedContributors = Object.entries(topContributors)
                .sort(([, a], [, b]) => b - a)
                .slice(0, 2);

              return (
                <div key={linkId} className="p-3 bg-muted/30 rounded-lg">
                  <div className="flex items-center justify-between mb-2">
                    <span className="font-medium">Link {linkId}</span>
                    <span className="text-sm font-mono">{events.length} events</span>
                  </div>
                  <div className="text-sm text-muted-foreground">
                    Top contributors: {sortedContributors.map(([cellId]) => `Cell ${cellId}`).join(", ")}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Recommendations */}
        <div className="section-card">
          <div className="flex items-center gap-2 mb-4">
            <Lightbulb className="w-5 h-5 text-chart-4" />
            <h3 className="font-semibold">Recommendations</h3>
          </div>
          <div className="space-y-3">
            {recommendations.map((rec, idx) => (
              <div key={idx} className="p-3 bg-muted/30 rounded-lg">
                <div className="flex items-center gap-2 mb-1">
                  <span
                    className={`text-[10px] font-bold uppercase px-1.5 py-0.5 rounded ${
                      rec.priority === "high"
                        ? "bg-status-low/20 text-status-low"
                        : rec.priority === "medium"
                        ? "bg-status-medium/20 text-status-medium"
                        : "bg-muted text-muted-foreground"
                    }`}
                  >
                    {rec.priority}
                  </span>
                  <span className="font-medium text-sm">{rec.title}</span>
                </div>
                <p className="text-xs text-muted-foreground">{rec.description}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Full Statistics */}
      <div className="section-card">
        <h3 className="font-semibold mb-4">Quick Statistics</h3>
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
          <div className="text-center p-4 bg-muted/30 rounded-lg">
            <div className="text-2xl font-bold text-primary">{totalCells}</div>
            <div className="text-xs text-muted-foreground">Total Cells</div>
          </div>
          <div className="text-center p-4 bg-muted/30 rounded-lg">
            <div className="text-2xl font-bold text-chart-2">{totalLinks}</div>
            <div className="text-xs text-muted-foreground">Links Detected</div>
          </div>
          <div className="text-center p-4 bg-muted/30 rounded-lg">
            <div className="text-2xl font-bold text-chart-3">{avgConfidence}%</div>
            <div className="text-xs text-muted-foreground">Avg Confidence</div>
          </div>
          <div className="text-center p-4 bg-muted/30 rounded-lg">
            <div className="text-2xl font-bold text-status-medium">{totalEvents}</div>
            <div className="text-xs text-muted-foreground">Congestion Events</div>
          </div>
          <div className="text-center p-4 bg-muted/30 rounded-lg">
            <div className="text-2xl font-bold text-status-high">{avgSavings}%</div>
            <div className="text-xs text-muted-foreground">Avg Savings</div>
          </div>
        </div>
      </div>
    </div>
  );
}
